blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/Harrisonlee0530, Dvorster, Coachyyds/root_finding/discussions
    about: Please ask and answer questions here.
